# Generated by Django 5.1.5 on 2025-03-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_userdetails_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
