# Generated by Django 5.1.5 on 2025-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('transaction', 'Transaction'), ('bill_payment', 'Bill Payment'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('password_forget', 'Password Forget'), ('payee_added', 'Payee Added')], max_length=50),
        ),
    ]
