# Generated by Django 5.1.5 on 2025-04-02 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_cnic_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15, message='CNIC must be exactly 15 digits.'), django.core.validators.RegexValidator(message='CNIC must only contains numbers.', regex='^\\d{15}$')]),
        ),
    ]
