# Generated by Django 5.1.5 on 2025-04-02 18:12

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(max_length=15, validators=[]),
        ),
    ]
