# Generated by Django 5.1.5 on 2025-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='PROMPTPAY', max_length=255),
        ),
    ]
