# Generated by Django 5.1.5 on 2025-03-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0002_bankaccount_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='PromptPay', max_length=255),
        ),
    ]
