# Generated by Django 5.1.5 on 2025-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0002_alter_payee_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rrn',
            field=models.CharField(default='0000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='stan',
            field=models.CharField(default='0000', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=50),
        ),
    ]
