# Generated by Django 5.1.5 on 2025-03-24 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0003_alter_bankaccount_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='transaction_limit',
        ),
    ]
