# Generated by Django 5.1.5 on 2025-03-24 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0004_remove_bankaccount_transaction_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('expiry_date', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=3)),
                ('card_type', models.CharField(default='Visa', max_length=20)),
                ('card_limit', models.DecimalField(decimal_places=2, default=50000.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
