# Generated by Django 5.1.5 on 2025-04-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0006_alter_transaction_rrn_alter_transaction_stan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='rrn',
        ),
    ]
