# Generated by Django 5.1.5 on 2025-03-25 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0007_payee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('bill_payment', 'Bill Payment'), ('subscription', 'Subscription')], max_length=20)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_account_title', models.CharField(max_length=255)),
                ('source_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('source_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('destination_account_title', models.CharField(max_length=255)),
                ('destination_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('consumer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('consumer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('channel', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
