# Generated by Django 5.1.5 on 2025-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0007_remove_transaction_rrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rrn',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
