# Generated by Django 5.1.5 on 2025-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0008_transaction_rrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rrn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stan',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
