# Generated by Django 5.1.5 on 2025-04-13 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_banking', '0009_alter_transaction_rrn_alter_transaction_stan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=255)),
                ('bill_type', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('water', 'Water'), ('internet', 'Internet')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
